In [1]:
import pandas as pd

# Open raw file
df = pd.read_csv('retail_sales_messy_100K.csv')
print(f"Before: {len(df)} rows")

Before: 101000 rows

Fix 1 — Remove duplicate orders

In [2]:
df = df.drop_duplicates(subset=['OrderID'])

,OrderID,OrderDate,Year,Month,MonthName,Quarter,Segment,Region,Category,SubCategory,...,CustomerID,Quantity,UnitPrice,Discount,Revenue,COGS,Profit,ProfitMargin,Channel,PaymentMethod
0,ORD-102874,2022-06-20,2022,6,Jun,Q2,Corporate,North,Furniture,Chairs,...,C3156,10,530.89,0.0015,4512.56,2481.91,2030.65,45.00,In-Store,Cash
1,ORD-62015,2022-04-24,2022,4,Apr,Q2,Corporate,West,Furniture,Cabinets,...,C5527,7,124.84,0.0010,786.49,432.57,353.92,45.00,In-Store,Cash
2,ORD-55860,2022-08-31,2022,8,Aug,Q3,Home Office,North,Furniture,Desks,...,C5120,1,361.01,0.0000,361.01,198.56,162.45,45.00,Mobile App,Cash
3,ORD-34080,2022-03-15,2022,3,Mar,Q1,Corporate,West,Electronics,Tablets,...,C9007,7,452.83,0.0025,2377.36,1545.28,832.08,35.00,Mobile App,Digital Wallet
4,ORD-51229,2023-12-16,2023,12,Dec,Q4,Consumer,Central,Electronics,Laptops,...,UNKNOWN,4,562.37,0.0000,2249.48,1462.16,787.32,35.00,Online,Digital Wallet
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100995,ORD-16266,2022-02-23,2022,2,Feb,Q1,Corporate,West,Clothing,Accessories,...,C6685,2,85.22,0.0010,153.40,76.70,76.70,50.00,Online,Debit Card
100996,ORD-64887,2023-06-13,2023,6,Jun,Q2,Corporate,East,Office Supplies,Staplers,...,C1343,9,56.66,0.0015,433.45,195.05,238.40,55.00,Online,Debit Card
100997,ORD-86821,2023-05-18,2023,5,May,Q2,Consumer,North,Office Supplies,Notebooks,...,C1754,10,62.30,0.0000,623.00,280.35,342.65,55.00,Online,Debit Card
100998,ORD-10861,18-Oct-2023,2023,10,Oct,Q4,Corporate,North,Office Supplies,Paper,...,C6464,5,5.74,0.0020,22.96,10.33,12.63,55.01,Online,Digital Wallet
100999,ORD-25796,2022-01-08,2022,1,Jan,Q1,Home Office,South,Furniture,Tables,...,C7468,5,30.99,0.0020,123.96,68.18,55.78,45.00,Online,Cash

Fix 2 — Remove negative quantity rows

In [3]:
df = df[df['Quantity'] > 0]

Fix 3 — Remove zero price rows

In [4]:
df = df[df['UnitPrice'] > 0]

Fix 4 — Fix discount scale if values are like 50, 30

In [5]:

if df['Discount'].max() > 1:
    df['Discount'] = df['Discount'] / 100

Fix 5 — Fill empty CustomerID with UNKNOWN

In [6]:
df['CustomerID'] = df['CustomerID'].fillna('UNKNOWN')

Fix 6 — Delete rows where ProductName is empty

In [7]:
df = df.dropna(subset=['ProductName'])

 Fix 7 — Remove extra spaces from ProductName

In [8]:
df['ProductName'] = df['ProductName'].str.strip()

Fix 8 — Fix region name capitalization

In [9]:
df['Region'] = df['Region'].str.strip().str.title()

In [17]:
df

,OrderID,OrderDate,Year,Month,MonthName,Quarter,Segment,Region,Category,SubCategory,...,CustomerID,Quantity,UnitPrice,Discount,Revenue,COGS,Profit,ProfitMargin,Channel,PaymentMethod
0,ORD-102874,2022-06-20,2022,6,Jun,Q2,Corporate,North,Furniture,Chairs,...,C3156,10,530.89,0.0015,4512.56,2481.91,2030.65,45.00,In-Store,Cash
1,ORD-62015,2022-04-24,2022,4,Apr,Q2,Corporate,West,Furniture,Cabinets,...,C5527,7,124.84,0.0010,786.49,432.57,353.92,45.00,In-Store,Cash
2,ORD-55860,2022-08-31,2022,8,Aug,Q3,Home Office,North,Furniture,Desks,...,C5120,1,361.01,0.0000,361.01,198.56,162.45,45.00,Mobile App,Cash
3,ORD-34080,2022-03-15,2022,3,Mar,Q1,Corporate,West,Electronics,Tablets,...,C9007,7,452.83,0.0025,2377.36,1545.28,832.08,35.00,Mobile App,Digital Wallet
4,ORD-51229,2023-12-16,2023,12,Dec,Q4,Consumer,Central,Electronics,Laptops,...,UNKNOWN,4,562.37,0.0000,2249.48,1462.16,787.32,35.00,Online,Digital Wallet
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100995,ORD-16266,2022-02-23,2022,2,Feb,Q1,Corporate,West,Clothing,Accessories,...,C6685,2,85.22,0.0010,153.40,76.70,76.70,50.00,Online,Debit Card
100996,ORD-64887,2023-06-13,2023,6,Jun,Q2,Corporate,East,Office Supplies,Staplers,...,C1343,9,56.66,0.0015,433.45,195.05,238.40,55.00,Online,Debit Card
100997,ORD-86821,2023-05-18,2023,5,May,Q2,Consumer,North,Office Supplies,Notebooks,...,C1754,10,62.30,0.0000,623.00,280.35,342.65,55.00,Online,Debit Card
100998,ORD-10861,18-Oct-2023,2023,10,Oct,Q4,Corporate,North,Office Supplies,Paper,...,C6464,5,5.74,0.0020,22.96,10.33,12.63,55.01,Online,Digital Wallet
100999,ORD-25796,2022-01-08,2022,1,Jan,Q1,Home Office,South,Furniture,Tables,...,C7468,5,30.99,0.0020,123.96,68.18,55.78,45.00,Online,Cash

In [10]:
print(f"After: {len(df)} rows")

After: 95859 rows

Save the clean file

In [11]:
df.to_csv('retail_sales_clean.csv', index=False)
print("Clean file saved!")

Clean file saved!